### ISSUE TITLE
ProPOSE did not respond to the registration application

### ISSUE THREAD

**Issue by kong0706** [giaguaro/PROTACable#1]
Hello, I have a high interest in PROTACable, but ProPOSE did not respond to the registration application, so I am currently unable to use it. May I ask if PrPOSE has alternative software? Can you provide some suggestions?

**Comment by giaguaro** [comment]
Hello, NRC may take some time to reply but they eventually do. You must ensure you have requested the license using valid academic credentials and that your academic institution has a valid signing authority (PI) to undertake the user agreement. The software is free of charge to use in academic labs. Unfortunately, no alternatives we can suggest as this integrates well with the command line flow and Amber atom typing.
